export interface LifeListTemplate {
  id: string;
  name: string;
  description: string;
  emoji: string;
  items: string[];
}

export const CURATED_TEMPLATES: LifeListTemplate[] = [
  {
    id: "couples-adventure",
    name: "Couples Adventure",
    description: "Experiences to share with your partner",
    emoji: "💕",
    items: [
      "Watch a sunrise together",
      "Take a spontaneous road trip",
      "Learn to cook a new cuisine together",
      "Stargaze away from the city",
      "Have a picnic in a beautiful spot",
      "Take a dance class together",
      "Write love letters to each other",
      "Visit a place neither of you has been",
      "Create a photo album of your journey",
      "Plan a surprise date for each other",
      "Build something together",
      "Watch your favorite childhood movies",
      "Try a new adventure sport",
      "Plant a tree or garden together",
      "Recreate your first date",
    ],
  },
  {
    id: "solo-growth",
    name: "Solo Growth Journey",
    description: "Personal milestones and discoveries",
    emoji: "🌱",
    items: [
      "Travel solo to a new place",
      "Learn a new skill or hobby",
      "Write a letter to your future self",
      "Meditate for 30 days straight",
      "Read 12 books in a year",
      "Take yourself on a solo date",
      "Learn to cook your favorite dish",
      "Start a journal practice",
      "Complete a fitness challenge",
      "Volunteer for a cause you care about",
      "Learn basic phrases in a new language",
      "Create something with your hands",
      "Face a fear you've been avoiding",
      "Spend a day in complete silence",
      "Write down 100 things you're grateful for",
    ],
  },
  {
    id: "friendship-goals",
    name: "Friendship Goals",
    description: "Adventures with your closest friends",
    emoji: "👯",
    items: [
      "Plan a friends trip together",
      "Start a tradition that's just yours",
      "Take a class together",
      "Create a group playlist",
      "Have a movie marathon night",
      "Do a fun photoshoot together",
      "Try a new restaurant every month",
      "Play a new board game or video game",
      "Go on a hiking adventure",
      "Host a themed dinner party",
      "Learn something new together",
      "Support each other at an event",
      "Create matching friendship items",
      "Write appreciation letters to each other",
      "Plan a surprise celebration",
    ],
  },
  {
    id: "family-moments",
    name: "Family Moments",
    description: "Memories to create with family",
    emoji: "👨‍👩‍👧‍👦",
    items: [
      "Cook a family recipe together",
      "Create a family photo album",
      "Start a family tradition",
      "Plan a family reunion",
      "Record stories from elders",
      "Take a multi-generational trip",
      "Plant a family tree (literal or digital)",
      "Create a time capsule",
      "Have a tech-free family day",
      "Learn about your ancestry together",
      "Volunteer as a family",
      "Build or create something together",
      "Watch old family videos",
      "Recreate an old family photo",
      "Write letters to each other",
    ],
  },
  {
    id: "wellness-journey",
    name: "Wellness Journey",
    description: "Taking care of mind, body, and soul",
    emoji: "🧘",
    items: [
      "Try a new form of exercise",
      "Complete a digital detox weekend",
      "Learn to meditate",
      "Sleep 8 hours for a full week",
      "Try a new healthy recipe each week",
      "Take a mental health day",
      "Practice gratitude daily for a month",
      "Go for nature walks regularly",
      "Try yoga or stretching",
      "Drink more water consistently",
      "Establish a morning routine",
      "Read about wellness and self-care",
      "Try a spa day at home",
      "Practice deep breathing exercises",
      "Declutter your living space",
    ],
  },
  {
    id: "creative-pursuits",
    name: "Creative Pursuits",
    description: "Unleashing your artistic side",
    emoji: "🎨",
    items: [
      "Learn to play a musical instrument",
      "Take a painting or drawing class",
      "Write a short story or poem",
      "Learn photography basics",
      "Make a short film or video",
      "Try pottery or ceramics",
      "Design something digitally",
      "Learn calligraphy or lettering",
      "Create a scrapbook",
      "Try a new craft (knitting, origami, etc.)",
      "Compose a song or melody",
      "Build something from scratch",
      "Start a creative journal",
      "Learn graphic design basics",
      "Create art to gift someone",
    ],
  },
  {
    id: "adventure-seeker",
    name: "Adventure Seeker",
    description: "For those who love thrills",
    emoji: "🏔️",
    items: [
      "Go skydiving",
      "Try scuba diving or snorkeling",
      "Climb a mountain",
      "Go camping under the stars",
      "Try bungee jumping",
      "Learn to surf",
      "Go on a safari",
      "Try paragliding",
      "Explore a cave",
      "Go white water rafting",
      "Take a hot air balloon ride",
      "Try zip-lining",
      "Go on a multi-day hike",
      "Learn rock climbing",
      "Visit a remote island",
    ],
  },
  {
    id: "cultural-explorer",
    name: "Cultural Explorer",
    description: "Discovering arts, history, and traditions",
    emoji: "🎭",
    items: [
      "Visit a world-renowned museum",
      "Attend a live theater performance",
      "Learn about a new culture's traditions",
      "Try authentic cuisine from different countries",
      "Attend a cultural festival",
      "Learn a traditional dance",
      "Visit historical landmarks",
      "Read literature from different cultures",
      "Learn about world religions",
      "Attend an opera or symphony",
      "Visit an art gallery",
      "Try traditional crafts from other cultures",
      "Watch international films",
      "Attend a poetry reading",
      "Visit a place of historical significance",
    ],
  },
];

export function getTemplateById(id: string): LifeListTemplate | undefined {
  return CURATED_TEMPLATES.find((t) => t.id === id);
}

export function getTemplateNames(): { id: string; name: string; emoji: string }[] {
  return CURATED_TEMPLATES.map((t) => ({
    id: t.id,
    name: t.name,
    emoji: t.emoji,
  }));
}
